module.exports = {
         compliments: [
            'Your smile is contagious.',
            'You look great today.',
            "You're a smart cookie.",
            'I bet you make babies smile.',
            'You have impeccable manners.',
            'I like your style.',
            'You have the best laugh.',
            'I appreciate you.',
            'You are the most perfect you there is.',
            'You are enough.',
            "You're strong.",
            'Your perspective is refreshing.',
            "You're an awesome friend.",
            'You light up the room.',
            'You shine brighter than a shooting star.',
            'You deserve a hug right now.',
            'You should be proud of yourself.',
            "You're more helpful than you realize.",
            'You have a great sense of humor.',
            "You've got all the right moves!",
            "Is that your picture next to 'charming' in the dictionary?",
            'Your kindness is a balm to all who encounter it.',
            "You're all that and a super-size bag of chips.",
            "On a scale from 1 to 10, you're an 11.",
            'You are brave.',
            "You're even more beautiful on the inside than you are on the outside.",
            'You have the courage of your convictions.',
            'Your eyes are breathtaking.',
            'If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.',
            'You are making a difference.',
            "You're like sunshine on a rainy day.",
            'You bring out the best in other people.',
            'Your ability to recall random factoids at just the right time is impressive.',
            "You're a great listener.",
            'How is it that you always look great, even in sweatpants?',
            'Everything would be better if more people were like you!',
            'I bet you sweat glitter.',
            'You were cool way before hipsters were cool.',
            'That color is perfect on you.',
            'Hanging out with you is always a blast.',
            'You always know -- and say -- exactly what I need to hear when I need to hear it.',
            'You smell really good.',
            "You may dance like no one's watching, but everyone's watching because you're an amazing dancer!",
            'Being around you makes everything better!',
            "When you say, 'I meant to do that,' I totally believe you.",
            "When you're not afraid to be yourself is when you're most incredible.",
            "Colors seem brighter when you're around.",
            "You're more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
            "That thing you don't like about yourself is what makes you so interesting.",
            "You're wonderful.",
            'You have cute elbows. For reals!',
            'Jokes are funnier when you tell them.',
            "You're better than a triple-scoop ice cream cone. With sprinkles.",
            'Your bellybutton is kind of adorable.',
            'Your hair looks stunning.',
            "You're one of a kind!",
            "You're inspiring.",
            "If you were a box of crayons, you'd be the giant name-brand one with the built-in sharpener.",
            'You should be thanked more often. So thank you!!',
            "Our community is better because you're in it.",
            "Someone is getting through something hard right now because you've got their back.",
            'You have the best ideas.',
            'You always know how to find that silver lining.',
            'Everyone gets knocked down sometimes, but you always get back up and keep going.',
            "You're a candle in the darkness.",
            "You're a great example to others.",
            'Being around you is like being on a happy little vacation.',
            'You always know just what to say.',
            "You're always learning new things and trying to better yourself, which is awesome.",
            'If someone based an Internet meme on you, it would have impeccable grammar.',
            'You could survive a Zombie apocalypse.',
            "You're more fun than bubble wrap.",
            'When you make a mistake, you fix it.',
            'Who raised you? They deserve a medal for a job well done.',
            "You're great at figuring stuff out.",
            'Your voice is magnificent.',
            'The people you love are lucky to have you in their lives.',
            "You're like a breath of fresh air.",
            "You're gorgeous -- and that's the least interesting thing about you, too.",
            "You're so thoughtful.",
            'Your creative potential seems limitless.',
            'Your name suits you to a T.',
            "You're irresistible when you blush.",
            'Actions speak louder than words, and yours tell an incredible story.',
            'Somehow you make time stop and fly at the same time.',
            'When you make up your mind about something, nothing stands in your way.',
            'You seem to really know who you are.',
            'Any team would be lucky to have you on it.',
            "In high school I bet you were voted 'most likely to keep being awesome.'",
            'I bet you do the crossword puzzle in ink.',
            'Babies and small animals probably love you.',
            "If you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer).",
            "You're someone's reason to smile.",
            "You're even better than a unicorn, because you're real.",
            'How do you keep being so funny and making everyone laugh?',
            'You have a good head on your shoulders.',
            'Has anyone ever told you that you have great posture?',
            'The way you treasure your loved ones is incredible.',
            "You're really something special.",
            "You're a gift to those around you.",
            'You deserve better.'
        ],
        monkeyfacts:[
        "Monkeys can understand written numbers and can even count. They can also understand basic parts of arithmetic and even, in rare cases, multiplication.",
        "To attract a female partner, male capuchin monkeys will urinate in their hands and then rub it thoroughly into their fur.",
        "Raw and cooked brain of dead monkey is widely consumed in China and Malaysia.",
        "Scientists observed female monkeys teaching their young how to floss their teeth.",
        "The smallest monkey in the world is the pygmy marmoset, with a body as little as 5 inches (12 cm) and a tail length of about 7 inches (17 cm). As a comparison, they are about the size of a hamster, can fit in the palm of a human hand, and they weigh the same as a pack of cards.",
        "Apes, gibbons, lemurs, and chimpanzees are not scientifically classified as monkeys. They are all primates, but, like humans, they have a different classification to monkeys.",
        "The most recently discovered monkey is the lesula monkey. It was discovered in 2007 in the Democratic Republic of the Congo in Africa.",
        "At the tip of a monkey's tail is a patch of bare skin that acts similar to a human's fingertips. It is sensitive to touch and also has tiny ridges that gives the tail a better grip.",
        "Monkeys that live in Central and South America are called \"New World monkeys.\" Monkeys that live in Africa and Asia are called \"Old World monkeys.\"",
        "Mandrill monkeys have fangs that are longer than a lion's fangs. They also have multi-colored bottoms which makes them easier to see in the leafy gloom of the forest."
        ],
        horsefacts: [
            'Horses can sleep standing up by locking their leg joints.',
            'Horses experience REM (rapid eye movement) during sleep, which means they most likely dream.',
            'The Hindus associate the horse with the cosmos, and a white horse was considered the last incarnation of Vishnu.',
            'The word “chivalry” comes from the French cheval, meaning horse.',
            'Some horses are able to figure out how to undo the doors of other horses and let them out.',
            'The earliest member of the horse family is the appropriately named “dawn horse,” or “Eohippus.” It dates back 55 million years.',
            'The horse head in the famous horse scene in The Godfather was actually a real, decapitated horse head.',
            'Unlike humans, horses have a functioning appendix that digests leaves, leading some scientist to believe that the human appendix may have had a similar function.',
            "Horses drink a lot of water, at least 25 gallons of water a day. In fact, water makes up 50% of a horse's total body weight.",
            'A horse’s teeth never stop growing.',
            'Feeding a horse cut grass can give them colic.',
            'In the early 20th century, cars were seen as an environmentally friendly solution to horse drawn carriages because horse poop and carcasses polluted the city. One city horse could produce between 15 and 30 pounds of manure day.',
            'In 1900, there were 15,000 horses in New York City. They produced enough manure in one year to create a pile 175 feet high, covering an acre of land, and breeding 16 billion flies.',
            'A horse has only one functional toe on each foot and its thick toenail is actually the hoof. It makes contact with the ground like a ballet dancer en pointe.',
            'In literature, art, and dream theory, the horse is often a symbol imbued with various meanings, ranging from power to beauty and even sexual prowess.In literature, art, and dream theory, the horse is often a symbol imbued with various meanings, ranging from power to beauty and even sexual prowess.',
            'The goddess Demeter (the goddess of fertility, grain, and the pure) had as her image a black mare’s head, and her priestesses were considered her “foals.”',
            'Horses have a strong band of muscles around their esophagus. This band is so strong that a horse’s stomach would burst before it would vomit.',
            'Though the word “hippopotamus” means “river horse,” a hippo is actually more closely related to the pig than the horse.',
            'Horses, zebras, and asses (as well as other equids) belong to the Order Perissodactyla, which is Greek from “odd-numbered finger or toe.',
            'The oldest animal carving ever found is of horse. It dates back 31,000 years in southern Germany.',
            'When a horse curls up its upper lip and bares its teeth, it\'s not laughing at you; it’s directing scents toward a special olfactory gland in the back of its nasal passage.',
            'There are about 58 million horses in the world.',
            'The horses’ closest relative is not the cow, pig, or goat--but the rhinoceros.',
            'Arab horses are one of the strongest endurance runners in the animal kingdom and are capable of running over 100 miles (160 km) without rest.',
            'Author John Trotwood Moore once states “Wherever Man has left his footprint in the long ascent from barbarism or civilization, we find the hoof print of a horse beside it.”',
            'According to the Bible, four horses will usher in the apocalypse.'
        ],
        dogfacts: [
            'Puppies have 28 teeth and adult dogs have 42.',
            'Hollywood’s first and arguably best canine superstar was Rin Tin Tin, a five-day-old German Shepherd found wounded in battle in WWI France and adopted by an American soldier, Lee Duncan. He would sign his own contracts with his paw print.',
            "Spiked dog collars were used to protect dogs' throats from wolf attacks in ancient Greece.",
            'Chocolate contains a substance known as theobromine (similar to caffeine) which can kill dogs or, at the very least, make them violently ill.',
            "A dog's whiskers are used as sensing devices.",
            'Dogs judge objects first by their movement, then by their brightness, and lastly by their shape.',
            "n ancient China, an emperor's last line of defense was a small Pekingese dog literally hidden up his sleeve.",
            'Greyhounds appear to be the most ancient dog breed. "Greyhound" comes from a mistake in translating the early German name Greishund, which means "old (or ancient) dog," not from the color gray.',
            'There are about 400 million dogs in the world.',
            'Dogs with little human contact in the first three months typically don’t make good pets.',
            'Endal was the first dog to ride on the London Eye (the characteristic ferris wheel in London, England), and was also the first known dog to successfully use a ATM machine.',
            'Dogs’ only sweat glands are between their paw pads.',
            'Dogs can count up to five and can perform simple mathematical calculations.',
            'Dogs can see best at dawn and dusk.',
            'Zorba, an English mastiff, is the biggest dog ever recorded. He weighed 343 pounds and measured 8’ 3" from his nose to his tail.',
            'Dogs have a wet nose to collect more of the tiny droplets of smelling chemicals in the air.',
            'It pays to be a lap dog. Three dogs (from First Class cabins!) survived the sinking of the Titanic – two Pomeranians and one Pekingese.',
            'A dog’s vision is not fully developed until after the first month.',
            'The smallest dog on record was a matchbox-size Yorkshire Terrier. It was 2.5" tall at the shoulder, 3.5" from nose tip to tail, and weighed only 4 ounces.',
            'The Beagle came into prominence in the 1300s and 1400s during the days of King Henry VII of England. Elizabeth I was fond of Pocket Beagles, which were only 9" high.',
            'Chase that tail! Dogs chase their tails for a variety of reasons: curiosity, exercise, anxiety, predatory instinct or, they might have fleas! If your dog is chasing his tail excessively, talk with your vet.',
            'Irish Wolfhounds, the tallest breed, are 30 to 35 inches tall.',
            'Growing up. While the Chow Chow dogs are well known for their distinctive blue-black tongues, they’re actually born with pink tongues. They turn blue-black at 8-10 weeks of age.',
            'Greyhounds are the fastest dogs on earth, with speeds of up to 45 miles per hour.',
            'Rock star Ozzy Osborne saved his wife Sharon’s Pomeranian from a coyote by tackling and wresting the coyote until it released the dog.',
            'In addition to "formal" forms of dog training (operant conditioning, reinforcement, or classical conditioning), dogs are able to learn merely from observation.',
            'Some dogs can smell dead bodies under water, where termites are hiding, and natural gas buried under 40 feet of dirt. They can even detect cancer that is too small to be detected by a doctor and can find lung cancer by sniffing a person’s breath.',
            'U.S. Customs dogs "Rocky" and "Barco" were so good at patrolling the border that Mexican drug lords put a $300,000 bounty on their heads.',
            'Different smells in the a dog’s urine can tell other dogs whether the dog leaving the message is female or male, old or young, sick or healthy, happy or angry.',
            'Dogs can see in color, though they most likely see colors similar to a color-blind human. They can see better when the light is low.',
            'One of Shakespeare’s most mischievous characters is Crab, the dog belonging to Launce in the Two Gentlemen of Verona. The word "watchdog" is first found in The Tempest.',
            'The oldest dog on record – a Queensland Heeler named Bluey – was 29 years, 5 months old.',
            'Teddy Roosevelt’s dog, Pete, ripped a French ambassador’s pants off at the White House.',
            'Obesity is the top health problem among dogs.',
            'The Mayans and Aztecs symbolized every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.',
            'The Labrador Retriever has been the most popular dog breed since 1991.',
            'Dogs’ nose prints are as unique as a human’s finger prints, and can be used to accurately identify them.',
            'When "Bobbie," a Collie/Shepherd mix, was accidentally abandoned on a family vacation, he traveled 2,551 miles over six months to return to his home.',
            'Analysis of the dog genome demonstrate only 4 major types of dogs: "Old Lineage Dogs," "Mastiff-type Dogs," "Herding Dogs," and "Modern Hunting Dogs."',
            'Davy Crockett had a dog named Sport.',
            'Dogs live an average of 15 years.',
            'The dog was frequently depicted in Greek art, including Cerberus, the three-headed hound guarding the entrance to the underworld, and the hunting dogs which accompanied the virgin goddess of the chase, Diana.',
            'Puppies sleep 90% of the day for their first few weeks.',
            'Many foot disorders in dogs are simply an issue of too-long toenails.',
            'A Russian dog named Laika was the first animal in space, traveling around Earth in 1957.',
            'Move over Rover! 45% of dogs sleep in their owner’s bed (we’re pretty sure a large percentage also hog the blankets!)',
            'Dogs with a flesh colored nose is said to have a "Dudley Nose."',
            'Fifty-eight percent of people put pets in family and holiday portraits.',
            'The U.S. has the highest dog population in the world.',
            'Newfoundlands are great swimmers because of their webbed feet.',
            'The Berger Picard, Miniature American Shepherd and Lagotto Romagnolo are the newest dog breeds recognized by the American Kennel Club in 2015.',
            'During the Middle Ages, mixed breeds of peasants’ dogs were required to wear blocks around their necks to keep them from breeding with noble hunting dogs. Purebred dogs were very expensive and hunting became the province of the rich.',
            'The Chihuahua was named after the state in Mexico where they were discovered.',
            'Teams of dogs compete for the fastest time without errors in Flyball races.',
            'Three of the 12 dogs on the Titanic survived.',
            'Bichons, Portuguese Water Dogs, Kerry Blue Terriers, Maltese and Poodles are all good choices if you have allergies since they shed less than other breeds.',
            'Petting a dog can lower your blood pressure.',
            'One survey reports that 33% of dog owners admit they talk to their dogs on the phone or leave messages on answering machines while they are away..',
            'Dogs are naturally submissive to any creature with a higher pack status.',
            'Dogs are naturally submissive to any creature with higher pack status, human or canine.',
            'President Lyndon Johnson had two beagles named Him and Her.',
            'Humans can detect sounds at 20,000 times per second, while dogs can sense frequencies of 30,000 times per second.',
            'The most dogs ever owned by one person were 5,000 Mastiffs owned by Kublai Khan.',
            'There are an estimated 400 million dogs in the world.',
            'More than one in three U.S. families owns a dog.',
            "Dogs don't enjoy being hugged as much as humans and other primates. Canines interpret putting a limb over another animal as a sign of dominance.",
            'The phrase "raining cats and dogs" originated in 17th century England when it is believed that many cats and dogs drowned during heavy periods of rain.',
            'The ancient religion Zoroastrianism includes in its religious text titled the Zend Avesta a section devoted to the care and breeding of dogs.',
            'The bible mentions dogs 14 times.',
            'Boxers are so named because of their manner of playing using their front paws.',
            'During the Renaissance, detailed portraits of the dog as a symbol of fidelity and loyalty appeared in mythological, allegorical, and religious art throughout Europe, including works by Leonardo da Vinci, Diego Velázquez, Jan van Eyck, and Albrecht Durer.',
            'Petting dogs is proven to lower blood pressure of dog owners.',
            'Smaller breeds mature faster than larger breeds.',
            'Dogs have no sense of time.',
            'In 2001, it was estimated that there are approximately 400 million dogs in the world.',
            'At the end of WWI, the German government trained the first guide dogs for war-blinded soldiers.',
            'Dogs sleep for an average of 10 hours per day.',
            'Dogs have been used since the 1700’s for therapy.',
            'Smaller breeds of dogs mature faster than larger breeds.',
            'A dog’s pregnancy lasts for approximately 60 days.',
            'Seventy percent of people sign their pet’s name on greeting and holiday cards.',
            'French poodles did not originate in France but in Germany ("poodle" comes from the German pudel or pudelhund, meaning "splashing dog"). Some scholars speculate the poodle’s puffs of hair evolved when hunters shaved the poodle for more efficient swimming, while leaving the pom-poms around the major joints to keep them warm.',
            'In 1957, Laika became the first living being in space via an earth satellite and JFK’s terrier, Charlie, fathered 4 puppies with Laika’s daughter.',
            'The most popular dog breed in Canada, U.S., and Great Britain is the Labrador retriever.',
            "Although it was once illegal to keep dogs as pets in Iceland's capital city, the laws have been relaxed.",
            'The Basenji is the only barkless dog.',
            'Dogs are capable of understanding up to 250 words and gestures, can count up to five and can perform simple mathematical calculations. The average dog is as intelligent as a two-year-old child.',
            'Basset Hounds cannot swim.',
            'The phrase "raining cats and dogs" originated in seventeenth-century England. During heavy rainstorms, many homeless animals would drown and float down the streets, giving the appearance that it had actually rained cats and dogs.',
            'The Labrador is so popular, in 2006 there were approximately 3-5 times more Labs as there were German Shepherds or Golden Retrievers.',
            'Male dogs will raise their legs while urinating to aim higher on a tree or lamppost because they want to leave a message that they are tall and intimidating. Some wild dogs in Africa try to run up tree trunks while they are urinating to appear to be very large.',
            'Even with their poor eyesight, dogs can still see better at night than humans do.',
            'An elderly woman was saved by her 12-pound Yorkshire Terrier, who fought off an 80- pound Akita, and survived with only 9 stitches.',
            'Unlike cats, dogs are not exclusively carnivores: they can adapt to different foods, and a percentage of their diets can be fruits and vegetables.',
            'Female wolves have been known to travel great distances to regurgitate full meals for their hungry pups.',
            'There are hundreds of breeds of dogs.',
            'In Egypt, a person bitten by a rabid dog was encouraged to eat the roasted liver of a dog infected with rabies to avoid contracting the disease. The tooth of a dog infected with rabies would also be put in a band tied to the arm of the person bitten. The menstrual blood of a female dog was used for hair removal, while dog genitals were used for preventing the whitening of hair.',
            'Dogs can get jealous when their humans display affection toward someone or something else.',
            'Weird dog laws include allowing police offers in Palding, Ohio, to bite a dog to quiet it. In Ventura County, California, cats and dogs are not allowed to have sex without a permit.',
            'The largest dog was an English Mastiff who weighed 343 pounds.'
        ]
    }
